name: Weekly Firestore Backup

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i firebase-admin

      - name: Write service account JSON
        run: |
          CRED_FILE="$RUNNER_TEMP/creds.json"
          printf '%s' "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > "$CRED_FILE"
          node -e "JSON.parse(require('fs').readFileSync(process.env.RUNNER_TEMP + '/creds.json','utf8')); console.log('Service account JSON OK')"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$CRED_FILE" >> "$GITHUB_ENV"

      - name: Run backup
        run: node backup.js

      - name: Commit backup
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add backups || true
          git commit -m "Weekly Firestore backup [skip ci]" || echo "No changes"
          git push || true